### ISSUE TITLE
UnboundLocalError: local variable 'post' referenced before assignment

### ISSUE THREAD

**Issue by Raviu56** [CatUnderTheLeaf/telegram_channel_backup#1]
Hello,
I think I've setup everything as required but I'm getting this error:
```
Traceback (most recent call last):
  File "/home/runner/work/sturdy-barnacle/sturdy-barnacle/telegram_channel_backup/backup_telegram_channel.py", line 109, in <module>
    asyncio.run(main(config['bot_token']))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/work/sturdy-barnacle/sturdy-barnacle/telegram_channel_backup/backup_telegram_channel.py", line 88, in main
    if 'photo_id' in post.keys():
UnboundLocalError: local variable 'post' referenced before assignment
Error: Process completed with exit code 1.
```

**Comment by CatUnderTheLeaf** [comment]
Thank you for opening this issue.
I think this happens because there are also some telegram service messages, like 'change channel name'.
I have added a small fix, I hope it fixes this issue, because I can't check it on the phone. If not, I will look at it in two weeks.
Thanks again for a good test case.

**Comment by Raviu56** [comment]
The reason was that I'd to wait 24 hours after adding bot to the channel.

**Comment by Raviu56** [comment]
It's working now any way thanks @CatUnderTheLeaf
